language: java
git:
  depth: 5
  submodules: false # we do this ourselves later with `build.py update`

matrix:
  include:
    - jdk: oraclejdk8
      env: PYTHON=python2
    - jdk: oraclejdk8
      env: PYTHON=python3
    - jdk: openjdk11
      env: PYTHON=python3

install:
  - export TOMCAT_VERSION=8.5.29
  - export BUILD_PY=./build/build.py
  - $PYTHON $BUILD_PY update-shallow
  - travis_retry $PYTHON $BUILD_PY dldeps

script:
  - $PYTHON --version
  - travis_retry $PYTHON $BUILD_PY build
  - $PYTHON $BUILD_PY check
  - $PYTHON $BUILD_PY test
  - $PYTHON $BUILD_PY war
  - jar xf ./build/dist/vnu.war && file WEB-INF/classes/nu/validator/servlet/VerifierServlet.class | grep "version 52.0"
  - curl -O http://archive.apache.org/dist/tomcat/tomcat-8/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.zip
  - unzip apache-tomcat-$TOMCAT_VERSION.zip
  - chmod a+x apache-tomcat-$TOMCAT_VERSION/bin/*.sh
  - apache-tomcat-$TOMCAT_VERSION/bin/catalina.sh start
  - cp ./build/dist/vnu.war apache-tomcat-$TOMCAT_VERSION/webapps/
  - timeout --preserve-status 15s tail -f apache-tomcat-$TOMCAT_VERSION/logs/catalina.out || true
  - curl -sS 'http://localhost:8080/vnu/?out=gnu&doc=data:text/html;charset=utf-8,%3C%21doctype%20html%3E%3Cmeta%20charset%3Dutf-8%3E%3Ctitle%3ETest%3C%2Ftitle%3E' > RESULTS
  - test -z "$(if [ -t RESULTS ]; then cat RESULTS | grep -v '^$'; fi)"
  - if [ $? != 0 ]; then cat RESULTS; fi
  - $PYTHON $BUILD_PY jar
  - java -jar ./build/dist/vnu.jar ./build/dist/index.html
  - java -jar ./build/dist/vnu.jar ./site/nu-about.html
  - jar xf ./build/dist/vnu.jar && file nu/validator/client/SimpleCommandLineValidator.class | grep "version 52.0"

cache:
  directories:
    - dependencies

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0b2024df5e6f10f19952
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

deploy:
  draft: true
  overwrite: true
  provider: releases
  file_glob: true
  file:
    - "build/dist/*.zip"
    - "build/dist/*.zip.md5"
    - "build/dist/*.zip.sha1"
    - "build/dist/*.jar"
    - "build/dist/*.jar.md5"
    - "build/dist/*.jar.sha1"
  skip_cleanup: true
  on:
    repo: validator/validator
  api_key:
    secure: "Rx95y6BDpQSCPkWr8FqUByet61U7z1Tqo3KrRm2AN2MLbch9YcX8KScvH3Mmtk3wEsdOTsgLt6SYxBrU/7RKLKlvUTaIRFecQm/hZuhThLcd91q40Oy3KcedSsUUaYljRbvg/nh6MeloVOvDM5VitqV07NwykA0pVrSqoFJDBHA="
