language: java
git:
  depth: 5
  submodules: false # we do this ourselves later with `checker.py update`

branches:
  except:
    - /^(osx|linux|windows|jar|war)$/

env:
  global:
    - TOMCAT_VERSION=8.5.29
    - CHECKER_PY=./checker.py
    - TRAVIS_TAG=linux
    - PYTHON=python3

matrix:
  include:
    - os:  linux
      jdk: openjdk8
    - os:  linux
      jdk: openjdk11
      env:
        - TRAVIS_TAG=jar
    - os:  linux
      jdk: openjdk11
      env:
        - TRAVIS_TAG=war
    - os:  osx
      env:
        - TRAVIS_TAG=osx
        - JAVA_HOME=$(/usr/libexec/java_home)
    - os:  windows
      jdk: openjdk11
      env:
        - TRAVIS_TAG=windows
    - os:  linux
      jdk: openjdk15
    - os:  linux
      jdk: openjdk16
    - os:  linux
      jdk: openjdk-ea

install:
  - $PYTHON --version
  - $PYTHON $CHECKER_PY update
  - travis_retry $PYTHON $CHECKER_PY dldeps
  - curl -O https://archive.apache.org/dist/tomcat/tomcat-8/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.zip
  - unzip apache-tomcat-$TOMCAT_VERSION.zip
  - chmod a+x apache-tomcat-$TOMCAT_VERSION/bin/*.sh

script:
  - $PYTHON $CHECKER_PY build
  - $PYTHON $CHECKER_PY jar
  - java -jar ./build/dist/vnu.jar ./build/dist/index.html
  - java -jar ./build/dist/vnu.jar ./site/nu-about.html
  - jar xf ./build/dist/vnu.jar && file nu/validator/client/SimpleCommandLineValidator.class | grep "version 52.0"
  - $PYTHON $CHECKER_PY runtime-image
  - $PYTHON $CHECKER_PY war
  - jar xf ./build/dist-war/vnu.war && file WEB-INF/classes/nu/validator/servlet/VerifierServlet.class | grep "version 52.0"
  - apache-tomcat-$TOMCAT_VERSION/bin/catalina.sh start
  - cp ./build/dist-war/vnu.war apache-tomcat-$TOMCAT_VERSION/webapps/
  - sleep 15s; tail apache-tomcat-$TOMCAT_VERSION/logs/catalina.out || true
  - curl -sS 'http://localhost:8080/vnu/?out=gnu&doc=data:text/html;charset=utf-8,%3C%21doctype%20html%3E%3Cmeta%20charset%3Dutf-8%3E%3Ctitle%3ETest%3C%2Ftitle%3E' > RESULTS
  - test -z "$(if [ -t RESULTS ]; then cat RESULTS | grep -v '^$'; fi)"
  - if [ $? != 0 ]; then cat RESULTS; fi
  - $PYTHON $CHECKER_PY check
  - $PYTHON $CHECKER_PY test

cache:
  directories:
    - dependencies

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0b2024df5e6f10f19952
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always

before_deploy:
  - openssl aes-256-cbc -K $encrypted_88088d7aed65_key -iv $encrypted_88088d7aed65_iv
    -in resources/ssh_travis.enc -out resources/ssh_travis -d
  - chmod 600 resources/ssh_travis
  - cat resources/ssh_known_hosts >> ~/.ssh/known_hosts
  - chmod 600 ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - ssh-add resources/ssh_travis
  - ls -al build/dist
  - ls -al build/dist-war
  - git config --local user.name "Travis CI"
  - git config --local user.email "mike@w3.org"
  - git push --delete git@github.com:validator/validator.git $TRAVIS_TAG || true
  - git tag -m $TRAVIS_TAG -f $TRAVIS_TAG

deploy:
  - provider: releases
    overwrite: true
    prerelease: true
    file_glob: true
    skip_cleanup: true
    file: "build/dist/{*.jar*}"
    on:
      condition: $TRAVIS_TAG = "jar"
      repo: validator/validator
      jdk: openjdk11
    api_key:
      secure: "LeO/Egf5TYyPAyTCMKkeIlqwcJInXcH3pZGSoT3eMd7Wmt1gWTwpBBN6lDm+ftouWLoGNi6cJ2W+ky5XjHLsO+80UN05T9LC6aoDO658fG0E770ApIUJf858HQCzrb56G2uBYRXkFqk3LrjBY+w8tVaqLijdFiDOSD+2OKmatU0="
  - provider: releases
    overwrite: true
    prerelease: true
    file_glob: true
    skip_cleanup: true
    file: "build/dist-war/{*.war*}"
    on:
      condition: $TRAVIS_TAG = "war"
      repo: validator/validator
      jdk: openjdk11
    api_key:
      secure: "LeO/Egf5TYyPAyTCMKkeIlqwcJInXcH3pZGSoT3eMd7Wmt1gWTwpBBN6lDm+ftouWLoGNi6cJ2W+ky5XjHLsO+80UN05T9LC6aoDO658fG0E770ApIUJf858HQCzrb56G2uBYRXkFqk3LrjBY+w8tVaqLijdFiDOSD+2OKmatU0="
  - provider: releases
    overwrite: true
    prerelease: true
    file_glob: true
    skip_cleanup: true
    file: "build/dist/{*.zip,*zip.md5,*.zip.sha1}"
    on:
      condition: $TRAVIS_TAG != "jar" && $TRAVIS_TAG != "war"
      repo: validator/validator
      jdk: openjdk11
    api_key:
      secure: "LeO/Egf5TYyPAyTCMKkeIlqwcJInXcH3pZGSoT3eMd7Wmt1gWTwpBBN6lDm+ftouWLoGNi6cJ2W+ky5XjHLsO+80UN05T9LC6aoDO658fG0E770ApIUJf858HQCzrb56G2uBYRXkFqk3LrjBY+w8tVaqLijdFiDOSD+2OKmatU0="
  - provider: releases
    overwrite: true
    prerelease: true
    file_glob: true
    skip_cleanup: true
    file: "build/dist/{*.zip*}"
    on:
      condition: $TRAVIS_TAG != "jar" && $TRAVIS_TAG != "war"
      repo: validator/validator
      os:  osx
    api_key:
      secure: "LeO/Egf5TYyPAyTCMKkeIlqwcJInXcH3pZGSoT3eMd7Wmt1gWTwpBBN6lDm+ftouWLoGNi6cJ2W+ky5XjHLsO+80UN05T9LC6aoDO658fG0E770ApIUJf858HQCzrb56G2uBYRXkFqk3LrjBY+w8tVaqLijdFiDOSD+2OKmatU0="
