name: Linux build for vnu

on:
  push:
    branches: [main]
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - 16
          - 11
          - 8
          - 17-ea
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Update submodules
        run: python ./checker.py update
      - name: Install dependencies
        run: python ./checker.py dldeps
      - name: Build
        uses: ./.github/actions/build
      - name: Import GPG signing key
        uses: crazy-max/ghaction-import-gpg@v3
        if: matrix.java == 16 && github.ref == 'refs/heads/main'
        with:
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          passphrase: ${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true
      - name: Sign release artifacts
        if: matrix.java == 16 && github.ref == 'refs/heads/main'
        run: |
          for file in build/dist/{*.zip,*.zip.md5,*.zip.sha1}; do gpg --yes -ab --sign $file; done || true
          for file in build/dist/*.jar*; do gpg --yes -ab --sign $file; done || true
          for file in build/dist-war/*.war*; do gpg --yes -ab --sign $file; done || true
      - name: Release new linux binary image
        uses: "marvinpinto/action-automatic-releases@latest"
        if: matrix.java == 16 && github.ref == 'refs/heads/main'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "linux"
          files: build/dist/*.zip*
      - name: Release new jar
        uses: "marvinpinto/action-automatic-releases@latest"
        if: matrix.java == 16 && github.ref == 'refs/heads/main'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "jar"
          files: build/dist/*.jar*
      - name: Release new war
        uses: "marvinpinto/action-automatic-releases@latest"
        if: matrix.java == 16 && github.ref == 'refs/heads/main'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "war"
          files: build/dist-war/*.war*
